@startuml
actor User as U
entity Escrow as E #purple
entity "Payment Registry" as PR #blue
control "Order Processor" as OP
control "Order from Accepted Blocks Processor" as ABP
database Database

ABP -[#purple]> E : Gets Orders from Accepted Blocks
ABP -> Database : Stores missing orders
ABP -> OP : Processes missing Order
OP -> OP : Processes Order
OP -[#blue]> PR : Transfers funds
PR -[#blue]> U: Transfers funds
OP -[#blue]> PR : Sends proof of payment
PR -[#purple]> E : Sends proof of payment
OP -> Database : Stores Order as completed

@enduml

