@startuml
actor User as U
entity Escrow as E #purple
entity "Payment Registry" as PR #blue
control "Order Processor" as OP
control "Failed Order Processor" as FOP
database Database

U -[#purple]> E : Sets Order
OP -[#purple]> E : Gets Order
OP ->x OP : Processes Order
OP -> Database : Stores Order as failed due to an error
FOP -> Database : Gets failed orders
FOP -> OP : Processes failed order
OP -[#blue]> PR : Transfers funds
PR -[#blue]> U: Transfers funds
OP -[#blue]> PR : Sends proof of payment
PR -[#purple]> E : Sends proof of payment
OP -> Database : Stores Order as completed

@enduml
