@startuml
actor User as U
entity Escrow as E #purple
entity "Payment Registry" as PR #blue
control "Order Processor" as OP
database Database

U -[#purple]> E : Set Order
OP -[#purple]> E : Get Order
OP -> Database : Store Order
OP -> OP : Processing Order
OP -[#blue]> PR : Transfer funds
PR -[#blue]> U: Transfer funds
OP -[#purple]> E : Repay funds
OP -> Database : Store Order as completed


@enduml
