import os
from dotenv import load_dotenv

load_dotenv()

ENVIRONMENT = os.getenv('ENVIRONMENT')

ETHEREUM_CHAIN_ID = os.getenv('ETHEREUM_CHAIN_ID')
STARKNET_CHAIN_ID = int(os.getenv('STARKNET_CHAIN_ID'), 16)
ZKSYNC_CHAIN_ID = int(os.getenv('ZKSYNC_CHAIN_ID'))

ETHEREUM_RPC = os.getenv('ETHEREUM_RPC')
STARKNET_RPC = os.getenv('STARKNET_RPC')
ZKSYNC_RPC = os.getenv('ZKSYNC_RPC')

ETHEREUM_FALLBACK_RPC = os.getenv('ETHEREUM_FALLBACK_RPC')
STARKNET_FALLBACK_RPC = os.getenv('STARKNET_FALLBACK_RPC')
ZKSYNC_FALLBACK_RPC = os.getenv('ZKSYNC_FALLBACK_RPC')

ETHEREUM_CONTRACT_ADDRESS = os.getenv('ETHEREUM_CONTRACT_ADDRESS')
STARKNET_CONTRACT_ADDRESS = os.getenv('STARKNET_CONTRACT_ADDRESS')
ZKSYNC_CONTRACT_ADDRESS = os.getenv('ZKSYNC_CONTRACT_ADDRESS')

ETHEREUM_PRIVATE_KEY = os.getenv('ETHEREUM_PRIVATE_KEY')
STARKNET_WALLET_ADDRESS = os.getenv('STARKNET_WALLET_ADDRESS')
STARKNET_PRIVATE_KEY = os.getenv('STARKNET_PRIVATE_KEY')

HERODOTUS_API_KEY = os.getenv('HERODOTUS_API_KEY')
HERODOTUS_ORIGIN_CHAIN = '5'
HERODOTUS_DESTINATION_CHAIN = 'SN_GOERLI'

MAX_RETRIES = 30
RETRIES_DELAY = 60  # 60 seconds, 30 tries within 30 minutes

POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_DATABASE = os.getenv('POSTGRES_DATABASE')

LOGGING_LEVEL = os.getenv('LOGGING_LEVEL')
LOGGING_DIRECTORY = os.getenv('LOGGING_DIRECTORY')

PAYMENT_CLAIMER = os.getenv('PAYMENT_CLAIMER')

SQL_LITE_DATABASE_URL = "sqlite:///:memory:"
